#!/bin/bash
#SBATCH --nodes=3
#SBATCH --time=03:59:00
#SBATCH --job-name=NYSERDA_20200515
#SBATCH --account=lljs
#SBATCH --mail-user=eliot.quon@nrel.gov
#SBATCH --mail-type=ALL

source $HOME/.bash_profile
wrf-env

ln -sf $WRFDIR/run/[aBbCcEGgHikLmopRStUV]* .
ln -sf $WRFDIR/run/real.exe .
ln -sf $WRFDIR/run/wrf.exe .

echo "Starting WRF at: " $(date)

srun -n 108 ./real.exe &> real.out
tail -n 1 rsl.out.0000

srun -n 108 ./wrf.exe &> wrf.out
tail -n 1 rsl.out.0000

echo "WRF finished at: " $(date)
